name: Deploy to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 13
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew build -Dspring.profiles.active=prod
        env:
          SECRET: SECRET
          EXPIRATION_TIME: EXPIRATION_TIME
          DB_URL: DB_URL
          DB_USER: DB_USER
          DB_PASSWORD: DB_PASSWORD

  deploy:
    runs-on: ubuntu-latest
    needs: build-prod
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: recipiz-api
          package: './build/libs/*.jar'

      - name: Azure logout
        run: |
          az logout
