# This is a basic workflow to help you get started with Actions

name: Deploy to Azure

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 13
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew build -Dspring.profiles.active=prod
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set environment variables
        run: echo Expirations time set to $EXPIRATION_TIME!
        env:
          SECRET: SECRET
          EXPIRATION_TIME: EXPIRATION_TIME
          AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          AZURE_WEBAPP_NAME: recipiz-api
          DB_URL: DB_URL
          DB_USER: DB_USER
          DB_PASSWORD: DB_PASSWORD

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/build/libs/*.jar'

      # Azure logout
      - name: logout
        run: |
          az logout